### ISSUE TITLE
Circular import dependency when SRFI 60 is installed

### ISSUE THREAD

**Issue by ilammy** [ashinn/chibi-scheme#267]
Commit 00691b64f11225802b787b0920377c1f0fe29b10 introduced usage of SRFI 60 instead of withdrawn SRFI 33 if SRFi 60 is available. However, it does not work when the library is actually available.

I have [implemented](https://github.com/ilammy/srfi-60) SRFI 60 some time ago (precisely because I did not want to use the withdrawn SRFI 33). It worked then, but I did not actually need it until now. I was somewhat surprised when I saw _this_ after installing the SRFI 60 library:

```
ilammy@serendipity$ chibi-scheme
ERROR on line 517 of file /usr/local/share/chibi/init-7.scm: write-string: not an output-port
    import
```

It turns out that Chibi will load SRFI 60 as a transitive depedency in the most basic case: (scheme base) → (chibi string) → (chibi char-set base) → (chibi iset base) → (srfi 60). The tricky part starts when SRFI 60 is caught with (scheme base) in its import list. Circular dependencies are bad, Chibi fails to load the library, and then fails to print an error message because `current-error-port` has not been initialized yet.

I think it was incorrect to make Chibi's internal libraries to depend on some unspecified third-party library, exactly because this can cause such dependency cycles. We can ensure absence of dependency cycles if 1) Chibi's dependency graph does not contain cycles, 2) external libraries do not contain cycles, 3) Chibi's libraries never depend on external libraries (or vice versa).

Chibi can control its own code to satisfy (1). External libraries can be expected to be sane and to not contain dependency cycles between themselves, thus satisfying (2). However, external libraries are expected to depend on libraries provided by Chibi, e.g. (scheme base). So, to avoid the possibility of circular dependency, Chibi must be self-sufficient and import only libraries which it provides itself.

**Comment by ashinn** [comment]
Strange, I had specifically tested with a (srfi 60) present, and found a circularity, and had thought I removed them all.

The problem is there are implementations which have (srfi 60) support by default but not (srfi 33), and I want to make Chibi's standard libraries like (chibi string) available for other implementations.

Converting Chibi's (srfi 33) to (srfi 60) would break existing code (plus (srfi 33) has some nicer utilities). I could provide both natively in Chibi so we wouldn't pick up unintended third-party implementations, but I think I'll just change the cond-expand to prefer (srfi 33), i.e. change

(cond-expand
   ((library (srfi 60)) (import (srfi 60)))
   (else (import (srfi 33))))

to

(cond-expand
   ((library (srfi 33)) (import (srfi 33)))
   (else (import (srfi 60))))
