### ISSUE TITLE
Formal syntax: not all peculiar identifiers recognized

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#276]
Admittedly, these are edge cases but the parser used at the repl (didn't check the one of the `(scheme read)` library) does not recognise things like `+inf.0+inf.0` (delimited by a delimiter) as an identifier. (It throws an error `invalid complex infinity: +inf.0` in this case.)

Or do I misread section 7.1.1 of R7RS? Does it imply that anything that *starts* with `+i`, `-i` or `<infnan>` is not a peculiar identifier? But then, `+ij` shouldn't be recognised as a valid identifier, which the repl does.

**Comment by ashinn** [comment]
Yes, anything that _starts_ with any valid number and is not otherwise a number is not allowed as an identifier (and that applies to the +inf.0 prefix as much as +i).  Chibi is somewhat lax in still allowing some of these, which is an extension allowed by the standard (it "is an error" which means we can do what we want).  Probably I should make this more strict for better portability.

The correct complex syntax, if that's what you wanted, would require the trailing "i": +inf.0+inf.0i
