### ISSUE TITLE
js demo not working

### ISSUE THREAD

**Issue by Kipples** [ashinn/chibi-scheme#325]
When I run `make js` everything builds ok but the demo doesn't do anything clicking start program results in no output.

however through some testing I found that if I do `make clibs.c` then `make js` I get output (errors from trying to import emscripten but that is expected)

some more testing `make js` `make clean` then if I remove the 2 calls to `make clean` from chibi-scheme-emscripten and run `make js` again it works.

**Comment by ashinn** [comment]
I believe the proper order is:

  make clibs.c
  make js

I don't have emscripten installed right now to verify.

**Comment by Kipples** [comment]
this will get you close, but it doesn't give the stuff in the emscripten module the call to `integer-eval-script` will result in this 
```
called from <anonymous> on line 1064 of file ./lib/init-7.scm
called from <anonymous> on line 558 of file ./lib/init-7.scm
called from <anonymous> on line 638 of file ./lib/init-7.scm
Searching for modules exporting integer-eval-script ... 
... none found.
```

**Comment by mnieper** [comment]
At the moment, the build process is a bit convoluted. What works is the following:

```
chibi$ make dist-clean
chibi$ make chibi-scheme-emscripten
chibi$ mv chibi-scheme-emscripten /tmp
chibi$ make dist-clean
chibi$ mv /tmp/chibi-scheme-emscripten .
chibi$ make js
```

I don't know since when the intended build process broke. I'll have to take a closer look when I have more time. The problem is that `chibi-scheme-emscripten` needs to be built for the host system but with `PLATFORM=emscripten`. This build leaves the directory in a state in which no clean emscripten build is possible.

The best way to solve these problems is certainly to let the build process output the compiled files in a specially designed build directory.

**Comment by Kipples** [comment]
I ended up writing my own build script in cmake, you can see it here https://gist.github.com/Kipples/af624609c9f028e406f8a910a1a3296a
This solved the problems I was having and lets me use chibi-scheme in my project and compile with emscripten

**Comment by mnieper** [comment]
Before I am going to reinvestigate this issue and dive into the Makefiles again, I would like to ask whether there is a slight chance to convert the hand-written Makefiles into GNU autoconf-based ones? In the long run, this seems more easily maintainable and has the chance to actually increase portability of Chibi.

**Comment by ashinn** [comment]
As autoconf is a huge, bloated mess, and basically the antithesis to chibi, I'd have to say the chance is almost nil :)

**Comment by mnieper** [comment]
What a pity! To me, a well-written `configure.ac` and `Makefile.am` looks more beautiful than a Makefile where everything has to be coded by hand and all dependencies have to be tracked by hand. Of course, one should not look into the bowels of autoconf and automake (at least if one does not want to see a mess), but neither adds this bloat to Chibi itself, nor would a user of Chibi ever have to install autoconf to `./configure` and `make` it. And `./configure` would remember the options I had given to it, while with the current Makefile setup, I have to define my options for every invocation of `make` again and again.

Anyway, just my two cents, which still may not have convinced you. :-)

**Comment by ashinn** [comment]
There's no hand-coding of dependencies or duplication in the chibi makefile.  There are in fact no dependencies at all because chibi itself has no dependencies (by design).

Make is a beautiful little implementation of first-order logic - a prolog for the file system.  It's one of my favorite languages.  Autoconf is a collection of hacks, which even if you don't look at the internals encourages cargo-cult programming.
