### ISSUE TITLE
Datum labels in datum comments

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#340]
The following two programs give unexpected results:

```
$ cat program1.scm
(import (scheme base) (scheme write))

(define (infinite-list)
  '#0=(42 . #0#)
  #;'#0=())

(write-shared (infinite-list))
(newline)
$ chibi-scheme program1.scm
(42)
$ cat program2.scm
(import (scheme base) (scheme write))

(define (infinite-list)
  '#0=(42 . #0#)
  #;'#0=(1 . #0#))

(write-shared (infinite-list))
(newline)
$ chibi-scheme program2.scm
(42 1 . #<invalid immediate: 46>)
```

In both cases, the datum comment should be treated as whitespace per 2.2 of R7RS. In other words, the expected result would be `#0=(42 . #0#)` in both cases.

(Again, both examples are stripped down to the bare minimum to demonstrate the issue. In a real world program, the issue will show up if I copy-and-paste a large code section (including datum labels) and comment out one for testing. In this case, I don't want to have to rename all datum labels.)

(The reader I get with `chibi-scheme -R` also does not ignore datum labels when they appear in datum comments.)

**Comment by ashinn** [comment]
Both of these are illegal programs with undefined behavior.

Remember that the reader label syntax is not just for cyclic data structures, but for shared structure.  So the expression: `(list #0="x" "0")` evaluates to `("x" "x")`, even though no cycle is involved.

Similarly in both of your examples, the two different uses of `#0=` are inside the same top-level expression, so they must refer to the same reader label, resulting in a conflict ("is an error").

One _might_ consider reader labels inside `#;` comments a special case, but there are only two reasonable ways to handle this.  Either reader labels inside `#;` are shared, or they are not.  Since in general we want to be able to comment and uncomment these expressions, we must assume the labels are shared.

Note that this means, for instance, inside a single `define-library` you can only ever use `#0=` (or any other label) once!  But as I've mentioned before, allowing cyclic data structures in source code is widely unsupported and was probably a mistake in R7RS.  If you want your programs to be portable you should avoid this.

**Comment by mnieper** [comment]
> Similarly in both of your examples, the two different uses of #0= are inside the same top-level expression, so they must refer to the same reader label, resulting in a conflict ("is an error").

That was the reason why I put them in the same top-level expression, so that I could check the behaviour of the datum comment.

> One might consider reader labels inside #; comments a special case, but there are only two reasonable ways to handle this. Either reader labels inside #; are shared, or they are not. Since in general we want to be able to comment and uncomment these expressions, we must assume the labels are shared.

If this was the intention of R7RS, then the specification is not very clear in this regard IMHO. R7RS as written says in 2.2: `The lexical syntax includes several comment forms. Comments are treated exactly like whitespace."

If comments were really treated exactly like whitespace, I would have thought labels wouldn't be shared. Anyway, I am fine with the other interpretation (of active labels inside datum comments), but this may deserve some clarification on the errata page.
