### ISSUE TITLE
Getting full stack trace

### ISSUE THREAD

**Issue by alexander-v** [ashinn/chibi-scheme#381]
I am trying to get the full stack trace.

My code is
```scheme
(import (chibi))

(define (h)
    (print-stack-trace)
    1)

(define (g)
    (h))

(define (f)
    (g))

(display (f))
```

Running it I get
```
% ./chibi-run -f test.scm
  called from <anonymous> on line 13 of file test.scm
  called from <anonymous> on line 1064 of file lib/init-7.scm
  called from <anonymous> on line 558 of file lib/init-7.scm
  called from <anonymous> on line 637 of file lib/init-7.scm
1
```

However, if I change my code to
```scheme
(import (chibi))

(define (h)
    (print-stack-trace)
    1)

(define (g)
    (h)
    1)

(define (f)
    (g)
    1)

(display (f))
```
I get
```
% ./chibi-run test.scm
  called from g on line 7 of file test.scm
  called from f on line 11 of file test.scm
  called from <anonymous> on line 15 of file test.scm
  called from <anonymous> on line 1064 of file lib/init-7.scm
  called from <anonymous> on line 558 of file lib/init-7.scm
  called from <anonymous> on line 637 of file lib/init-7.scm
1
```
So the calls seem to be optimized away. Is there a way to disable this behavior and preserve callstack information?

**Comment by ashinn** [comment]
This is called tail-call optimization (TCO) as defined in section 3.5 of the R7RS.
It's very important not to disable this since Scheme relies on it to implement loops.
Strictly for debugging purposes we could consider disabling it, or tracking a fixed history of frames though.

**Comment by johnwcowan** [comment]
Or you could do what Chicken does, and just print out the last N calls, ignoring whether they have returned or not.  It's still pretty helpful.

**Comment by ashinn** [comment]
Chicken can do this because it uses Cheney-on-the-MTA, so the last N calls stay on the stack until after the next minor gc.  The only frames available in Chibi are the non-returned, non-tail calls.

**Comment by johnwcowan** [comment]
On Tue, Jan 10, 2017 at 6:23 PM, Alex Shinn <notifications@github.com>
wrote:

Chicken can do this because it uses Cheney-on-the-MTA, so the last N calls
> stay on the stack until after the next minor gc. The only frames available
> in Chibi are the non-returned, non-tail calls.


Well, it's easier for Chicken.  But you could stash the last N calls in a
fixed-size ring buffer.

-- 
John Cowan          http://vrici.lojban.org/~cowan        cowan@ccil.org
One Word to write them all / One Access to find them,
One Excel to count them all / And thus to Windows bind them.
                --Mike Champion

**Comment by ashinn** [comment]
Which is what I said originally, but it would be quite slow.  A compiler could allow a debug mode for this, but it's less convenient as a compile-time option for the chibi vm.

Instead I've added a very simple hack, just run chibi-scheme with a -T option, and it will disable tail calls entirely.  This gives a lot more frames than you'd expect, since we run programs via a "load" implemented in Scheme.  It's also only for debugging, since it becomes easy to run out of stack space.

**Comment by alexander-v** [comment]
Thank you!
