### ISSUE TITLE
Creating userdata in chibi

### ISSUE THREAD

**Issue by vaartis** [ashinn/chibi-scheme#490]
Lua has a notion of userdata: a pointer to raw memory that is managed by the GC. In chibi, however, i create my custom data with `sexp_alloc` and then, when the program finishes, chibi tries to finalize that data, but because it's not a valid sexp value, the `tag` on it is all messed up and as a result the program segfaults on trying to access memory outside of global type array.. Is there any way around it?

Minimal example:
```
    struct Testy {
        int func(int x) { return x + 1; }
    };

    void *allocated_place = sexp_alloc(chibi.context, sizeof(&Testy::func));
    auto allocated_in_chibi = new (allocated_place) decltype(&Testy::func)(&Testy::func);
```

sizeof a pointer to a member function is in worst case 16

**Comment by ashinn** [comment]
You can use sexp_make_cpointer to wrap untyped malloc'ed data which will be freed properly on exit:

`Testy* testy = (Testy*) malloc(sizeof(Testy));
sexp wrapped_testy = sexp_make_cpointer(ctx, SEXP_CPOINTER, testy, SEXP_FALSE, 1);`

More idiomatic would be to use the FFI to wrap the Testy type in Scheme.  If you specify (c++) it will use new and delete instead of malloc and free.

**Comment by vaartis** [comment]
The problem is that i want to store a member function pointer though. It's too big to fit into a `void*` type pointer.

**Comment by ashinn** [comment]
So malloc whatever size you need, put the member function pointer in there, and wrap the malloc'ed pointer.

Although I really think wrapping the type and storing instances would be cleaner.

**Comment by vaartis** [comment]
I see, thank you. I will try to do that.
