### ISSUE TITLE
SRFI 125: Hash functions

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#531]
Some SRFI 125 functions call SRFI 128 hash functions with two arguments, which is an error.

**Comment by ar-nelson** [comment]
Seconded, this bug is preventing me from using hash tables in Chibi. It can be replicated with a small Scheme program, `problem.scm`:

```scheme
(import (scheme base) (srfi 125) (srfi 128))
(define ht
  (make-hash-table (make-vector-comparator (make-default-comparator)
                                           vector?
                                           vector-length
                                           vector-ref)))
(hash-table-set! ht #(1 2) 'foo)
```

This program crashes with a "too many args" error:

```
$ chibi-scheme problem.scm
ERROR in final-resumer: too many args
    #<procedure #f>
    2
```

It seems like the problem is in SRFI 128, not SRFI 125. Chibi's SRFI 125 is implemented on top of SRFI 69, which expects two-argument hash functions. The SRFI 128 document [specifically warns about this possibility](https://srfi.schemers.org/srfi-128/srfi-128.html#Hashfunctions):

> ...if programmers wish their hash functions to be backward compatible with the reference implementation of SRFI 69, they are advised to write their hash functions to accept a second argument and ignore it.

The ideal solution would be to modify `make-comparator` in SRFI 128 to wrap the hash function in a lambda that takes a second argument and ignores it. I'll submit a PR that does this.

**Comment by vuolen** [comment]
Should this be closed?

**Comment by ashinn** [comment]
Yes.
