### ISSUE TITLE
(chibi match) bounded repetition

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#535]
There is no facility for bounded repetition in `(chibi match)` analogous to the `repeated` pattern of SRFI 115.  In particular, there is no way to make parts of a pattern optional.  Here are some alternatives:

1.  Add a general `repeat` pattern element like `(repeat 3 5 a)` which matches 3 to 5 copies of the same thing.

2.  Add a postfix `???` operator for the 0-or-1 case.  This can then be used like `a a a a ??? a ???`, which is not exactly so obvious but does work.

3.  Add a `null` pattern which matches nothing.  Then `a ???` is equivalent to `(or null a)`.

1 is obviously the clearest in the general case, but 2 may be sufficient.  3 is more of a minimalist hack.

**Comment by ashinn** [comment]
There is the `..k` syntax, which is the only feature of Wright's matcher not supported (except for the `..1` "one or more" special case).

Implementation is easy but a good syntax not obvious, since `..k` is not an option with syntax-rules.  In general this style of matcher relies on punctuation-like syntax instead of prefix, so `(repeat <n> <m> <p>)` doesn't fit.

`***` is taken for trees.  How about `..= <n>` for exact repetition and `..* <n> <m>` for a range?

**Comment by johnwcowan** [comment]
I can live with that, although it makes the postfix syntax into pseudo-infix.
