### ISSUE TITLE
Scripts and search path errors

### ISSUE THREAD

**Issue by ekaitz-zarraga** [ashinn/chibi-scheme#600]
I'm having a weird issue I don't know how to deal with.

I successfully created a script that loads some libraries declared locally but when I move to a different folder and I run the script from it, the interpreter is unable to find the libraries because the search path is `.` instead of the file's path.

How I'm supposed to deal with this?

Imagine I have some scripts I want to run by their own but all of them have a `utils` folder with some common libraries for all of them in the same folder. How am I supposed to handle this *very common* setup?

Thanks!

Example:

``` bash
$ find
.
./utils
./utils/bzip2.sld
./utils/bzip2.scm
./elf2c.scm

$ chibi-scheme elf2c.scm
 RUNS PERFECT

$ cd ..

$ chibi-scheme src_chibi/elf2c.scm 
ERROR on line 2 of file src_chibi/elf2c.scm: couldn't find import: (utils bzip2)
  called from <anonymous> on line 1285 of file /gnu/store/xnhrnr40g0ggh0n79gdp218sdsd5i00y-chibi-scheme-588d63d901984bdff9f62525a3cbbd3af9e7af92/share/chibi/init-7.scm
  called from <anonymous> on line 280 of file /gnu/store/xnhrnr40g0ggh0n79gdp218sdsd5i00y-chibi-scheme-588d63d901984bdff9f62525a3cbbd3af9e7af92/share/chibi/init-7.scm
  called from <anonymous> on line 813 of file /gnu/store/xnhrnr40g0ggh0n79gdp218sdsd5i00y-chibi-scheme-588d63d901984bdff9f62525a3cbbd3af9e7af92/share/chibi/init-7.scm
Searched module path ("./lib" "." "/gnu/store/xnhrnr40g0ggh0n79gdp218sdsd5i00y-chibi-scheme-588d63d901984bdff9f62525a3cbbd3af9e7af92/share/chibi" "/gnu/store/xnhrnr40g0ggh0n79gdp218sdsd5i00y-chibi-scheme-588d63d901984bdff9f62525a3cbbd3af9e7af92/lib/chibi") for "utils/bzip2.sld".

```

**Comment by hga** [comment]
Set the CHIBI_MODULE_PATH environment variable in your script?

Something like this should do the trick, it works from my command line from /tmp:

hga@redacted:/tmp$ CHIBI_MODULE_PATH="/home/src/chibi-scheme/lib:/home/src/persist/sdbi-chibi/lib" /home/src/chibi-scheme/chibi-scheme -m "(srfi sdbi)"

Where /home/src/persist/sdbi-chibi/lib contains srfi/sdbi.sld.

- Harold

----- Original message -----
From: "Ekaitz Zárraga" <notifications@github.com>
Date: Monday, January 06, 2020 11:50 AM
I'm having a weird issue I don't know how to deal with.
I successfully created a script that loads some libraries declared locally but when I move to a different folder and I run the script from it, the interpreter is unable to find the libraries because the search path is `.` instead of the file's path.

How I'm supposed to deal with this?

Imagine I have some scripts I want to run by their own but all of them have a `utils` folder with some common libraries for all of them in the same folder. How am I supposed to handle this *very common* setup?

Thanks!

**Comment by ekaitz-zarraga** [comment]
I was expecting something like I'm missing a way to handle it or whatever.
Also, I would be able to do that but not in a way that only works for my machine...
Has this a reason to be the way it is? Should it be like this?
How is this handled in other projects?

**Comment by Shamar** [comment]
As far as I can see by reading [run_main](https://github.com/ashinn/chibi-scheme/blob/master/main.c:#L295), we would just need to prepend `dirname(argv[0])` to the module search path.

Am I missing something?

**Comment by ekaitz-zarraga** [comment]
Maybe we are missing the reason. There's another issue related with this: #249 

What I wonder is if I'm the first one to consider this a problem and if there's a reason for this. Maybe there's a better way to load libraries I'm missing. I'm not sure.

How do other programmers manage this?

Until @ashinn answers if there's a design decision behind, I'll test  @Shamar 's suggestion locally and make a PR.

**Comment by Shamar** [comment]
@ekaitz-zarraga after a good sleep, I think that yesterday I was wrong in several ways. :-D

First I was talking about chibi-scheme scripts, using [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) but I forgot to clarify it.

Furthermore I was wrong about the whole shebang mechanics (which could provide a proper solution to this issue): when the kernel loader see a shebang it invokes the executable path that follows it and fills `argv` with its path, the arguments provided in the shebang line and then the arguments provided to the script itself.

So if you create a test.echo script like this:

    #!/bin/echo -p

make it executable and invoke it, you'll see

   $ ./test.echo
   -p ./test.echo
   $ cd subdir/
   $ ../test.echo
   -p ../test.echo
   $ ../test.echo Hola!
   -p ../test.echo Hola!

That's because argv is populated this way by the kernel:
   argv[0] = "/bin/echo";
   argv[1] = "-p";
   argv[2] = "../test.echo"; /* the original argv[0] given to exec() */
   argv[3] = "Hola!"; /* all other arguments provided to exec() */

So maybe the proper solution is to add an option to `run_main` so that it accepts a path to a script and
- prepend dirname(path) to the module search path
- load path
- execute main on it

____

@ashinn sorry for the noise in your issue tracker... I should really learn to avoid github when tired...

**Comment by ekaitz-zarraga** [comment]
I've been playing around with shebangs and it's possible to workaround this adding this kind of weird shebang:

```
#|
#!/usr/bin/env sh
exec chibi-scheme -A `dirname "$0"` $0 "$@"
|#
(import (chibi))
(display (command-line))
```

The approach is similar to the one that Guile uses.
It would be interesting btw to know why does this work this way and why isn't `dirname $0` in the module load path by default.

Cheers

**Comment by ashinn** [comment]
Basically including `.` is just a convenience during development and you shouldn't rely on that for installed scripts.  I may remove it in the future.  You _could_ use the shebang trick, which would continue to work.

The intention though is to install dependent libraries in the system path as is done by snow-chibi.

**Comment by lassik** [comment]
One option is doing something like this:

`/usr/local/bin/your-thing`:

```shell
#!/bin/sh
exec chibi-scheme -I /usr/local/libexec/your-thing \
    /usr/local/libexec/your-thing/main.scm "$@"
```

`/usr/local/libexec/your-thing/main.scm`:

```scheme
(import (part-of-your-thing))
(display "Hello world\n")
```

**Comment by lassik** [comment]
Sorry, should probably use `/usr/local/lib` instead of `libexec` since main.scm is not intended to be directly executable.

**Comment by ekaitz-zarraga** [comment]
> Basically including `.` is just a convenience during development and you shouldn't rely on that for installed scripts. I may remove it in the future. You _could_ use the shebang trick, which would continue to work.
> 
> The intention though is to install dependent libraries in the system path as is done by snow-chibi.

Fine, so... I should install all libraries which is fine but is there any way to work on separate environments of packages installed by snow?

I found snow has a way to set a place were non-root user packages can be installed, but chibi doesn't find packages there by default so... it doesn't really solve the issue of keeping different projects separated.

How do you deal with this particular case?
You just install everything in the system? Or do you manage to keep stuff separated?

Thanks

**Comment by ashinn** [comment]
This is just how packaging works on *nix systems - you either have a single global install, or you have to deal with path settings (for C LD_LIBRARY_PATH, for chibi CHIBI_MODULE_PATH and/or -A).

More recently containers are a popular way to manage this.  This is good for services and long-running programs, but less so for scripts.

**Comment by ekaitz-zarraga** [comment]
Yeah it is, but I needed something else for reasons...(guix and stuff) CHIBI_MODULE_PATH is more than enough for what I need. I'll manage to run with it. Thank you for your explanation. I'll close the issue.
