### ISSUE TITLE
(chibi syntax-case) fails on simple old-style macro definition

### ISSUE THREAD

**Issue by ds26gte** [ashinn/chibi-scheme#620]
Here's a trivial macro that should convert `(add x y)` to `(+ x y)`.

```
(import (chibi syntax-case))

(define-syntax add
  (lambda (so)
    (datum->syntax so
      (let* ((so-d (syntax->datum so))
             (a (cadr so-d))
             (b (caddr so-d)))
        `(+ ,a ,b)))))
```

Loading it into Chibi-Scheme version 0.8.0 "oxygen" and trying

```
(add 1 2)
```

produces 
```
ERROR in symbol->identifier on line 1126 of file /usr/local/share/chibi/init-7.scm: slot-ref: bad type
    "Sc"
    (add 1 2)
```

**Comment by mnieper** [comment]
The first argument of `datum->syntax` has to be an identifier. In your case, it is the (wrapped) syntax object corresponding to the form `(add x y)`. You have to unpack the form first to get hold of the identifier `add`. For that, you cannot use `syntax->datum` because it removes all syntactic context from `add`. You have to use `syntax-case`:

```
(define-syntax add
  (lambda (so)
    (syntax-case so ()
      ((k . _) ...))))

Now, you can use `#'k` in `...` to refer to the keyword `add` for use in `datum->syntax`.

**Comment by mnieper** [comment]
As no bug has been found, I think we can close the issue.

**Comment by ashinn** [comment]
Thanks Marc!
