### ISSUE TITLE
Mention that GNU Make is required to successfully build

### ISSUE THREAD

**Issue by edw** [ashinn/chibi-scheme#642]
I was pulling my hair out trying to build and install Chibi-Scheme from the repository until I looked at Homebrew's build and realized I was using Apple's BSD-ish `make` while `gmake` was called for.

**Comment by ashinn** [comment]
At least originally the gmake-specific uses were quite limited and I think there was a separate generic Makefile (without platform or feature detection) at one point.  Let me see if I can restore it.

**Comment by edw** [comment]
Thanks. Specifically, the problem I was running into was chibi-scheme would report that init-7.scm could not be found.

**Comment by mnieper** [comment]
Ceterum censeo Carthaginem esse delendam!

Let Automake generate the Makefiles, which won't depend on GNU make. ;)

**Comment by ashinn** [comment]
I think you're teasing me Marc.  You know I hate automake with the fire of a thousand suns.

**Comment by mnieper** [comment]
> I think you're teasing me Marc. 

As must Cato the Elder the members of the Roman Senate.

> You know I hate automake with the fire of a thousand suns.

What must have happened to you that you hate it so much? I prefer nicely written Makefiles, for which it is just the perfect tool. :) Anyway, it really makes sure to generate maximally portable Makefiles.

**Comment by lassik** [comment]
Autotools esse delendam. Since people keep wanting it, we should specify a minimal subset of Scheme, write an ultra-portable interpreter for that subset and and rewrite the essential parts of autotools in it. Everyone can be happy that way. (Well, everyone who likes the autotools interface, dislikes the autotools implementation, likes Scheme, and doesn't dislike reimplementations of de facto standard tools :p)

**Comment by pclouds** [comment]
Gauche actually reimplements (parts of) autoconf in scheme, in module gauche.configure. You can write configure script in scheme, basically. automake is a different story.

**Comment by mnieper** [comment]
People keep wanting it for a good reason. But even the Autotools maintainers will be happy if you rewrite it in, say, Guile. But note that you don't have to make Guile ultra-portable for that. Remember that the Autotools are not run on the user's machine.

(NB My specific comment from above was just about Automake. I mention this because I have met more people who mix up the various Autotools components and their purpose that I have met that don't.)

**Comment by lassik** [comment]
> Gauche actually reimplements (parts of) autoconf in scheme, in module gauche.configure. You can write configure script in scheme, basically. automake is a different story.

Great. We should probably start any such project from that basis.

> But even the Autotools maintainers will be happy if you rewrite it in, say, Guile. But note that you don't have to make Guile ultra-portable for that. Remember that the Autotools are not run on the user's machine.

While that is true, it would be better if the maintainer tools were much more portable as well. It's unlikely that autotools needs to do anything so fancy that the power of Guile is required.

Neither Guile nor the current shell-m4-make-... contraption are trivial to get going on esoteric systems either. Guile is a large download, a long build, and may involve a bootstrap. shell, m4 and make are heavily Unix-centric (and cryptic and brittle).

IMHO the main virtues of a build system are simplicity and portability. A bare-bones Scheme subset would be just the ticket. The interpreter could be one `.c` file, based on something like Mini-Scheme or its descendants. Builds are I/O bound so it doesn't need to be fast.

If the configuration system is done in Scheme, we could also potentially re-implement the main parts of `make` in Scheme and bundle it in the same system. Then separate configure scripts don't need to be generated. The system could also have a REPL. That's potentially  really cool.

> I have met more people who mix up the various Autotools components and their purpose that I have met that don't.

True. The system is somewhat hard to understand and most people don't really take the time to get familiar with build systems. Since autoconf is the part that breaks most often, perhaps people confuse the whole system with it.

**Comment by lassik** [comment]
Since this is Scheme, we could write a spec for the subset of the language used in the build system. It could even be a SRFI. Different Scheme implementations could implement the spec, so everyone can run the build system in their favorite Scheme. One person could run it in Guile, another in Chibi, a third in Gauche. We could supply a bare-bones reference implementation as one `.c` that is a hacked TinyScheme that runs anywhere. Everyone wins.

**Comment by mnieper** [comment]
@lassik Which esoteric maintainer systems do you know? It's harder to bootstrap C than to bootstrap Guile. :)

Anyway, it would be nice to have the Autotools re-written in Scheme (and, maybe, better integration in Guix, which is Scheme-based) because we are here because we prefer Scheme over Perl and Python. But we mustn't forget that Autotools "just work" and are simple to use. (When I use them, I don't care whether Shell or Perl code is running.) Rebuilding something with the same power will take a lot of work, work that is probably better invested in other areas to promote Scheme.

**Comment by lassik** [comment]
> Which esoteric maintainer systems do you know?

To start with, Windows :p

Other examples: BeOS/Haiku, AmigaOS, Minix, the emerging hobby OSes written in Rust...

> It's harder to bootstrap C than to bootstrap Guile. :)

Yes, going from nothing to C is probably harder than going from C to Guile. But running Scheme on a system where a binary C compiler isn't readily available is unlikely. In most cases (though not all!) you'd configure a Scheme implementation written in C, so a C compiler is needed anyway.

Anyway, if we specified a Scheme subset (in a SRFI for example) then Guile could implement that subset (which would probably be trivial by leveraging Guile's existing libraries). As could all the other big Schemes, more or less. People would have the freedom to use whichever one they have at hand or personally prefer, while software maintainers could write portable configure scripts and build scripts using the standard subset.

If the maintainers of a big software system decide that they only want to support Guile, they could rely on Guile-only features in parts of their project's build system. This would still leave more leeway to other projects who don't want to depend on a large Scheme implementation.

> Anyway, it would be nice to have the Autotools re-written in Scheme (and, maybe, therefore with better integration in Guix, which is Scheme-based) because we are here because we prefer Scheme over Perl and Python.

Definitely. Good goals all.

> But we mustn't forget that Autotools "just work" and are simple to use. (When I use them, I don't care whether Shell or Perl code is running.)

Autotools is very far from "just works". It breaks all the time when you venture outside the most popular versions of the most popular Linux distros. And when it breaks it's almost impossible to fix it unless you are a wizard. Writing it in Scheme would help a lot with making it comprehensible to mere mortals (at least if those mortals are Scheme/Lisp programmers :p).

You're right that the consistent user interface is very pleasant though. `./configure` options work the same way and the same `make` targets are always there. That's the main selling point and we'd do well to preserve it in a Scheme rewrite. (Instead of `make` we could possibly have a make work-alike written in Scheme, but it could support the same standard targets that GNU makefiles have.)

> Rebuilding something with the same power will take a lot of work,

Very true. The amount of painfully earned knowledge that went into Autotools is very respectable. It would have to be replicated piecemeal and would probably take quite a long time.

> work that is probably better invested in other areas to promote Scheme.

It need not be mutually exclusive. People cannot generally transfer energy freely from one problem to another, but work more efficiently on whatever strikes their fancy. I would be motivated to put some energy into build tools if an approach can be agreed upon, as it's a problem domain where Scheme's strengths (easy subsetting, cleanliness and expressive power with a minimal core) would especially shine.

**Comment by mnieper** [comment]
> > Which esoteric maintainer systems do you know?
> 
> To start with, Windows :p

Even Windows has WSL nowadays. :)

> > But we mustn't forget that Autotools "just work" and are simple to use. (When I use them, I don't care whether Shell or Perl code is running.)
> 
> Autotools is very far from "just works". It breaks all the time when you venture outside the most popular versions of the most popular Linux distros. And when it breaks it's almost impossible to fix it unless you are a wizard. Writing it in Scheme would help a lot with making it comprehensible to mere mortals (at least if those mortals are Scheme/Lisp programmers :p).

It's funny. I have never seen the Autotools break (apart from such bugs that are inherent in every software). What I do see regularly break are handwritten Makefiles and configure-scripts and autogenerated Makefiles in software packages whose author does not know how to write a `configure.ac` properly (and not just because they don't understand M4).

Rewriting it in Scheme won't help with the last point because it's the philosophy that some people do not understand.

> You're right that the consistent user interface is very pleasant though. `./configure` options work the same way and the same `make` targets are always there. That's the main selling point and we'd do well to preserve it in a Scheme rewrite. (Instead of `make` we could possibly have a make work-alike written in Scheme, but it could support the same standard targets that GNU makefiles have.)

If we do it in Scheme, we should do everything in Scheme. :) But we should write a Prolog in Scheme first to make it more declarative from the beginning.

**Comment by ashinn** [comment]
@mnieper: I've had to deal with a lot of projects which have a very broken autotools configuration.  That doesn't mean you can't use it correctly, but it's fragile, and is near impossible to debug if it breaks.  It also adds nothing of practical value.  In this case, the requirement to install GNU make (or tweak the few conditionals) is no more onerous than the requirement to install autotools.

@lassik: A hacked TinyScheme?  Inside Chibi?!  Chibi strips down to about the same size and arguably better portability.

**Comment by ashinn** [comment]
... and we're going to need the separate mkfile for Plan9 regardless.

**Comment by ashinn** [comment]
Actually this was mentioned in the makefiles themselves, I just highlighted it in the README, and moved all of the non-portable bits to Makefile.detect for easier overriding.

**Comment by lassik** [comment]
> Even Windows has WSL nowadays. :)

Yes, but it's not customary there.

> It's funny. I have never seen the Autotools break (apart from such bugs that are inherent in every software). What I do see regularly break are handwritten Makefiles and configure-scripts and autogenerated Makefiles in software packages whose author does not know how to write a `configure.ac` properly (and not just because they don't understand M4).
> 
> Rewriting it in Scheme won't help with the last point because it's the philosophy that some people do not understand.

I may be one of those people who have missed the philosophy behind it. Is it explained in a particular document or FAQ?

>> (Instead of `make` we could possibly have a make work-alike written in Scheme, but it could support the same standard targets that GNU makefiles have.)
> 
> If we do it in Scheme, we should do everything in Scheme. :) But we should write a Prolog in Scheme first to make it more declarative from the beginning.

Sounds reasonable.

> @mnieper: I've had to deal with a lot of projects which have a very broken autotools configuration. That doesn't mean you can't use it correctly, but it's fragile, and is near impossible to debug if it breaks. It also adds nothing of practical value. In this case, the requirement to install GNU make (or tweak the few conditionals) is no more onerous than the requirement to install autotools.

This is my experience with autotools as well.

> @lassik: A hacked TinyScheme? Inside Chibi?! Chibi strips down to about the same size and arguably better portability.

Not inside Chibi, but as the simplest reference implementation of the Scheme subset specified for writing the build system. Chibi could be another implementation; Gauche and Gambit could be others, etc. It would be quite easy to codify a reasonable subset of Scheme in a SRFI (plus a few extra primitives like OS stuff from SRFI 170 and a topological sort for makefiles) and write implementations for many existing Schemes. It would be mostly re-exporting stuff from RnRS.

While Chibi is very compact, there are a handful of Schemes like TinyScheme and S9 that have the virtue of being shipped entirely in one `.c` file. That makes the build ultra simple, which is good for a reference implementation.

If Chibi's build system were written in this proposed subset, Chibi could be built using an existing copy of itself, using another popular Scheme implementation, or using the reference implementation that ships in one `.c` file. The build (and configure) rules themselves could be written in `.scm` files using the specified Scheme subset.

This approach could be overkill for Chibi, but it could be a reasonable substitute for the many autotools/cmake projects - those configuration languages are as big as Scheme while lacking expressive power and beauty.

**Comment by lassik** [comment]
> ... and we're going to need the separate mkfile for Plan9 regardless.

The hacked TinyScheme implementation could be made to run on Plan9 with some `#ifdef`. And Chibi already runs there :)

**Comment by ashinn** [comment]
Cat the headers and gc.c, sexp.c, eval.c, vm.c, main.c together and Chibi is a single file.

**Comment by lassik** [comment]
Fair enough. That's 10K lines of code which is somewhat bigger than TinyScheme but not by much. Does Chibi work without an image file?

The beauty of having a specification is that it doesn't really matter which implementation is the reference one. It can be just one among many, or people can explore different approaches. The main thing would be the spec, and a canonical build system written in `.scm` files. (Like autotools, people could pick and choose which `.scm` files are good for their project, do project-specific extensions to them, etc.)

**Comment by ashinn** [comment]
Yes, images are only experimental in Chibi.
If you run with -q you get just the core language (init-7.scm).
If you run with -Q it doesn't even load any `.scm` files and you get just the core forms and primitives.

**Comment by mnieper** [comment]
> > It's funny. I have never seen the Autotools break (apart from such bugs that are inherent in every software). What I do see regularly break are handwritten Makefiles and configure-scripts and autogenerated Makefiles in software packages whose author does not know how to write a `configure.ac` properly (and not just because they don't understand M4).
> > Rewriting it in Scheme won't help with the last point because it's the philosophy that some people do not understand.
> 
> I may be one of those people who have missed the philosophy behind it. Is it explained in a particular document or FAQ?

The best introduction is, in my opinion, the book by John Calcote: https://nostarch.com/autotools2e

Some (draft?) version of the first edition is available in the Free Software Magazine: http://freesoftwaremagazine.com/books/autotools_a_guide_to_autoconf_automake_libtool/.

> > @mnieper: I've had to deal with a lot of projects which have a very broken autotools configuration. That doesn't mean you can't use it correctly, but it's fragile, and is near impossible to debug if it breaks. It also adds nothing of practical value. In this case, the requirement to install GNU make (or tweak the few conditionals) is no more onerous than the requirement to install autotools.
> 
> This is my experience with autotools as well.

Saying that Autotools add nothing of practical value is like saying that we can ditch C and return to assembly language. :)

Automake allows us to create clearly written Makefiles. Apart from purity reasons, this has a lot of practical value because we don't have to re-invent the wheel for the standard targets every time. When used right, we have Makefiles that allow out-of-directory builds, have a working distcheck, etc. I bet that every hand-written Makefile has at least one bug in this regard.

Autoconf allows us to abstract from specifics of the build system. If you look at Chibi's code, there are a lot of ifdefs testing various build systems. This is much more fragile than reusing the existing configure checks and the wisdom behind that are already in Autoconf.

The sentence "The requirement to install GNU make (or tweak the few conditionals) is no more onerous than the requirement to install autotools." shows that the Autotools really needs more and better explanation. :-/ The idea is that the majority of those that deal with the software are users who want to compile and install it. For them, the task should be as easy as possible. This means that those who want to run `./configure && make && make install` neither do have to install GNU make nor the Autotools. It is just the developers and maintainers that need the Autotools to rebuild the Makefiles and the configure script.

Anyway, Chibi has working Makefiles, so my initial comment was tongue-in-cheek; but for new software projects for the Unix world I would always recommend the Autotools for their zero cost. (Unless we have a Scheme-based build system, of course.)

@lassik If you want to push this further, maybe you should approach the Guix people. They already have a Scheme-based package management system; an integrated build system based on Scheme would be a perfect match.

**Comment by ashinn** [comment]
Chibi will always be full of ifdefs because it supports many systems and has many build options.  Autotools can't help with this.  What it could do in theory do is simplify some of the logic, e.g. where we infer SEXP_64_BIT from one of a list of known macros, but there are only a few of these cases it could help with and I like having the explicit list.

**Comment by lassik** [comment]
> The best introduction is, in my opinion, the book by John Calcote: https://nostarch.com/autotools2e
> 
> Some (draft?) version of the first edition is available in the Free Software Magazine: http://freesoftwaremagazine.com/books/autotools_a_guide_to_autoconf_automake_libtool/.

Thank you for the links. I'm reading them.

> I bet that every hand-written Makefile has at least one bug in this regard.

Indeed, it's practically impossible to manually write a Makefile with a complete and correct dependency graph ("recursive make considered harmful" is just a start). It's even harder than correctly doing memory allocation in C, which probably implies that humans shouldn't even be trying to do the task at all. We're just used to it because nothing better is ubiquitous.

> Autoconf allows us to abstract from specifics of the build system. If you look at Chibi's code, there are a lot of ifdefs testing various build systems. This is much more fragile than reusing the existing configure checks and the wisdom behind that are already in Autoconf.

which is also stated in https://nostarch.com/download/samples/Autotools2e_Sample_Ch2.pdf:

> [Autotools] makes your project incredibly portable—even to systems on which you’ve never tested, installed, or built your code.

Like Alex, I have the opposite opinion. This to me is the main failing of autoconf (apart from being implemented in brittle languages). Autoconf aspires to let people build software on systems that are unknown to the people who wrote that software. This is not generally possible, and this is where we get to the part where Autoconf often breaks and fails to deliver on its promise.

For best portability, programmers should be intimately familiar with the native conventions of different operating systems. It hurts more than helps if the intrinsic differences are hidden behind a veil such as autoconf. Without a true understanding of the target platforms, it's easy to produce configure failures or subtly incorrect results.

The ideal solution would be for the operating systems themselves to standardize, so that the native conventions are the same everywhere. POSIX is an obvious example where this has worked well. (POSIX has many flaws, but on the whole it's a big victory.) As long as OSes have divergent conventions, any solution other than hand-crafted per-OS configurations will be a hack. Autoconf is an automated hack; that makes it easy but it will also break easily. Automated solutions only work reliably when they are based on solid principles, which are not possible in this problem domain. It could be likened to automated regulatory compliance based on heuristics - the regulations are idiosyncratic to each country and follow no logic, so a principled solution is not possible.

Hence the `#ifdef`s are messy because they faithfully model a messy problem. Autoconf contains a generic mess that is an abstraction of the specific messes of different programs. In Alex's and my experience, the abstraction is very leaky, and a new layer of autoconf-specific `#ifdef`s are needed to use it.

> The idea is that the majority of those that deal with the software are users who want to compile and install it. For them, the task should be as easy as possible.

That would indeed be nice, and automake seems to genuinely help with it.

IMHO autoconf is a mixed blessing in this regard since there is no proof that an auto-generated configuration is correct and idiomatic to each target OS.

> @lassik If you want to push this further, maybe you should approach the Guix people. They already have a Scheme-based package management system; an integrated build system based on Scheme would be a perfect match.

I can talk to them, and it would indeed be great if Guix integration was easy. A Scheme-configured and "purely functional package management" based distro is a very nice idea.

I suspect that GNU folks would be happiest with something significantly more complex than I would aim for. Ideally we could arrive at a very modular solution for the build system, and write a spec for the underlying Scheme language that anyone can implement. Then the people who want simple things and the people who want complex things could still share code.

**Comment by lockywolf** [comment]
> The idea is that the majority of those that deal with the software are users who want to compile and install it. For them, the task should be as easy as possible.

This is practically far from reality, isn't it?

Machines that are likely to have make almost inevitably have autotools too. And it's especially unlikely that anyone who is not a developer is going to compile chibi from source. 

Even the most source-based Linux distros, such as Gentoo, guix, nix, or Source Mage have package management systems.

On the other hand, neither Windows not Android have make by default.

**Comment by lassik** [comment]
> Even the most source-based Linux distros, such as Gentoo, guix, nix, or Source Mage have package management systems.

Indeed, from this standpoint it's ideal if each program simply has a `config.h` file, and each packager overwrites that file with the right configuration for that distro. The packagers know the settings better than any automated solution, the division of labor is appropriate (programmer writes portable program, distro packagers take care of platform idiosyncrasies, and the two parties communicate to work out any problems), and the end result couldn't be simpler.

Where autoconf helps is when people want to build custom versions of software and install it in a custom location. Arguably this use case should also be fully supported by distro package managers, but they don't universally do so.

> On the other hand, neither Windows not Android have make by default.

Exactly. Adding a small, self-contained Scheme interpreter to a Windows project (one `.exe` file with no dependencies) is no harder than adding `make`. Also, if the build system is written in Scheme, Java projects could use a Java implementation of Scheme.

**Comment by mnieper** [comment]
> > [Autotools] makes your project incredibly portable—even to systems on which you’ve never tested, installed, or built your code.
> 
> Like Alex, I have the opposite opinion. This to me is the main failing of autoconf (apart from being implemented in brittle languages). Autoconf aspires to let people build software on systems that are unknown to the people who wrote that software. This is not generally possible, and this is where we get to the part where Autoconf often breaks and fails to deliver on its promise.

> For best portability, programmers should be intimately familiar with the native conventions of different operating systems. It hurts more than helps if the intrinsic differences are hidden behind a veil such as autoconf. Without a true understanding of the target platforms, it's easy to produce configure failures or subtly incorrect results.
> 
> The ideal solution would be for the operating systems themselves to standardize, so that the native conventions are the same everywhere. POSIX is an obvious example where this has worked well. (POSIX has many flaws, but on the whole it's a big victory.) As long as OSes have divergent conventions, any solution other than hand-crafted per-OS configurations will be a hack. Autoconf is an automated hack; that makes it easy but it will also break easily. Automated solutions only work reliably when they are based on solid principles, which are not possible in this problem domain. It could be likened to automated regulatory compliance based on heuristics - the regulations are idiosyncratic to each country and follow no logic, so a principled solution is not possible.

The main point, in my opinion, is that absolutism is misguided. Every software system has bugs because it is very hard to test it fully. As soon as I have N configuration options (Chibi has a lot of them, for example, making it very flexible, so this is a good thing), there are at least 2^N configurations of the software on a single system. You simply cannot think of every single interaction that may happen between two configuration options. So, at some point, someone will approach you and show you that some particular configuration does not work. You can fix it then (and it should be easy because you were foresightful and the basic infrastructure is already in place in your software).

From an abstract point of view (sorry, I'm still the mathematician), the idea of varying build systems is not fundamentally different from the idea of configuration options. This tells us two things: Knowing all your build systems does not help, and thinking that your configure script will work flawlessly everywhere is foolish. But should be easily able to fix it.

In any case, Autotools do not make the situation worse but at least give you some help in structuring your project wisely. It is still hard to write portable C code, though, for which we have software like Gnulib. (Most of its modules are licensed by the GPL, which I consider a boon, but those embracing the embrace of the open-source world by the four or five IT monopolists may not think so.)

Anyway, I will back out of this discussion because I need more important things to be done. ;) Although I don't like truisms, in this case, it is probably true that the truth is somewhere in the middle.

**Comment by lassik** [comment]
> The main point, in my opinion, is that absolutism is misguided. Every software system has bugs because it is very hard to test it fully.

Very true. It's interesting to note that the pro-autoconf and anti-autoconf camps base their opinions on the same argument. To me, autoconf is going for absolutism (i.e. absolute abstraction over systems' idiosyncrasies) where that is not possible.

> You simply cannot think of every single interaction that may happen between two configuration options.

Also true. Regretfully, the only real solution is to offer fewer options.

> From an abstract point of view (sorry, I'm still the mathematician), the idea of varying build systems is not fundamentally different from the idea of configuration options.

The difference is that build systems (by which I take you mean OS / compiler) are dictated by the environment and you have to conform to them. Whereas program-specific build options are completely under your control.

> thinking that your configure script will work flawlessly everywhere is foolish. But should be easily able to fix it.

This sums up the main argument against autoconf: since you have to fix portability problems anyway, the extra layer of abstraction from autoconf is superfluous and confusing. Autoconf proponents would claim the abstraction avoids so many common pitfalls that it's a net win; autoconf opposers would claim it fails often enough that the extra complexity is a net loss.

It's based on our individual experiences, and on aesthetics. I'm a strong proponent of minimalism, and especially minimalism in environmental dependencies, so I'm primed to have a negative opinion. Someone whose aesthetics place an especially high value on convenience and automation is primed to have a positive opinion.

It's important that one can favor tools like automake while simultaneously disfavoring tools like autoconf.

> Anyway, I will back out of this discussion because I need more important things to be done. ;) Although I don't like truisms, in this case, it is probably true that the truth is somewhere in the middle.

I respect that. Thanks for participating in the discussion - it has been enlightening.

The reason the truth lies somewhere in the middle is probably that any problem with either autotools or a manual system can ultimately be fixed (and the ultimate outcome is much the same: program X now works on system Y). The pain just occurs in a different part of the process, or falls on different people. And depending on which OS / software one uses, there is more or less pain in total. Much of my negative experiences with autotools come from exotic platforms (BSD or Apple) and exotic languages (i.e. not C/C++). The Linux and C build rules are much more polished so they rarely cause problems.

Anyway, as a practical outcome, a very modular Scheme system could be something that pleases everyone and still allows the different camps to work together to some extent. I'll try to experiment a bit by translating parts of autoconf and automake to a Scheme subset, and talking to the Guix folks. I'm almost certain we can't agree on a full system, but if it's modular and we can have multiple parallel implementations, it doesn't really matter.
