### ISSUE TITLE
Change `raise` to `raise-continuable` in misc-macros.scm

### ISSUE THREAD

**Issue by johnwcowan** [ashinn/chibi-scheme#661]
For rationale, see https://groups.google.com/forum/#!topic/comp.lang.scheme/J_EnOpOFBF4

**Comment by ashinn** [comment]
`raise-continuable` is the natural choice, which is no doubt why it was used originally.

But this issue is apparently so confusing that we not only added, but then later reverted an erratum, and I don't want to keep going back and forth.  I'm trying to recall the context.  Why was the erratum proposed in the first place?

**Comment by johnwcowan** [comment]
As far as I can make out, it all traces back to SRFI 34, when `guard` is invented, and is defined to call `raise` because `raise-continuable` doesn't exist.  That language is copied unreflectively into R6RS and corrected to `raise-continuable` in the R6RS errata.   Then it's copied from the uncor.rected R6RS into R7RS, and it gets corrected from the R6RS errata eventually.  Chibi switched to raise on Marc's advice, he told me, based on the R7RS.
