### ISSUE TITLE
Too many expressions allowed in syntax-rules template

### ISSUE THREAD

**Issue by jpellegrini** [ashinn/chibi-scheme#767]
Hello,
Chibi accepts `syntax-rules` templates as this:

```
(define-syntax f
  (syntax-rules ()
    ((f) 10 20 30 40)))

(f)  =>  10
```
So only the first item in the template (10) is used, the others are discarded. Other implementations signal an error on this.
(STklos also behaves like Chibi; I'm working on that)

**Comment by mnieper** [comment]
The template is extracted here: https://github.com/ashinn/chibi-scheme/blob/master/lib/init-7.scm#L1108. The length of the clause (as a list) is not checked.

That, by the way, illustrates one big advantage of the `syntax-case` system over `er-macro-transformer`: Unless you use non-standard helpers like `syntax->list` or `syntax-e`, it forces you to use `syntax-case` to destructure your macro input. If Chibi's `syntax-rules` had been written with `syntax-case`, we would have seen something like `(syntax-case clause () ((pat tmpl) ---))`, automatically catching all wrongly formed macro inputs.

So if you write things from the scratch for STklos, I would recommend using `syntax-case` to write `syntax-rules`.

(Of course, one can use a matcher like Wright's matcher for `er-macro-transformer`, but this gives only a third of the advantage of `syntax-case`. You would catch such an error as above, but you would use a different matcher than the usual syntax-rules matcher, which is ubiquitous when writing Scheme macros, and error reporting with precise line numbers would be much worse.)

**Comment by ashinn** [comment]
That's not even remotely an argument against er-macro-transformer, since this is the definition of the syntax-rules pattern matcher itself.  The same potential bug exists in the definition of syntax-case.  And there's nothing preventing you from defining your own pattern matchers to layer on top of er-macro-transformer.

**Comment by mnieper** [comment]
As I wrote, this does not apply to Chibi's `syntax-rules` implementation because Chibi has to be able to bootstrap itself. The same is true for the `syntax-case` implementation shipped with Chibi. But it wouldn't be true for implementations that bootstrap itself with an existing system as, say, Chez Scheme ([1]).

But that wasn't my point. I just mentioned what proponents of `syntax-case` have always presented as an advantage of that system, namely that parsing syntax with `car` and `cdr` is error-prone and brittle. Again, notwithstanding the fact that you cannot do it differently in `init-7.scm`.

I agree with you that layering a suitable pattern matcher (preferably the one used for `syntax-rules` to make it easy to move between the systems) on top of `er-macro-transformer` helps but then it probably looks like `syntax-case` so one can ask why not start with `syntax-case` in the first place. The difference would be that with the former you have to consciously choose to use the matcher and that with the latter you have to consciously choose to destructure your input into an s-expression first. All that I have been claiming is that with the latter approach, more people write fault-tolerant macros.

--

[1] https://github.com/cisco/ChezScheme/blob/main/s/syntax.ss#L6501

**Comment by lassik** [comment]
Does Chez Scheme require an R6RS implementation (implying `syntax-case` is available) from which to bootstrap itself?

Approximately how many lines of code is a syntax-case implementation "from scratch", i.e. starting from a small set of primitives like `(srfi 211 low-level)`? 1k, 5k, 10k, 15k lines?

**Comment by mnieper** [comment]
I'd suggest moving this to another list as it gradually becomes more off-topic. It's my fault because of my comment above. But just to give you an answer: Yes, Chez Scheme needs a suitable Scheme implementation to bootstrap itself. It's quite clever because it has to match the host implementations and its own syntax objects.

A `syntax-case` implementation based on a small set of primitives like the low-level R4RS primitives will be roughly as long as Alex's `syntax-rules` implementation in `init-7.scm` because it is the pattern matcher that has to be added to the low-level primitives.

**Comment by mnieper** [comment]
@ashinn If you agree, I will merge my fix (referenced above), which makes the `syntax-rules` parser a bit stricter by disallowing clauses with more than two forms.

**Comment by ashinn** [comment]
Yes, this is fine, I made a suggestion for a better error message.

**Comment by mnieper** [comment]
Merged with better error message.
