### ISSUE TITLE
Segmentation faults and/or memory leaks when compiling with C++ compiler

### ISSUE THREAD

**Issue by dpapavas** [ashinn/chibi-scheme#808]
I've been getting memory leaks, in the form of unfinalized foreign objects, and occasional segmentation faults, while trying to embed Chibi scheme into a C++ application.  Trying to reproduce the problems in a simple test case without success, I finally discovered that they only occur when the test case was compiled as C++ source (either with `g++`, or with `gcc -xc++`).

The behavior seems to depend on the entire contents of the test Scheme source, including portions that aren't immediately related to the (un)finalized objects.  Consider [this](https://github.com/ashinn/chibi-scheme/files/7833228/test.tar.gz) test program.  As is, it compiles and runs fine for me with:

`gcc test.c -g -O0 $(pkg-config --cflags --libs chibi-scheme)`

Fine, here, means that it doesn't crash and prints "foo" twice, indicating that both foreign objects have been finalized.

When compiled with:

`gcc -xc++ test.c -g -O0 $(pkg-config --cflags --libs chibi-scheme)`

It raises a segmentation fault, some time after collecting the first foreign object.  The immediate cause of the segfault is related to the following:
>invalid field access in gc.c line 450: 0x3e (-1) isn't a type

This makes it look like some sort of memory corruption is going on.  If you make virtually any substantial change to the Scheme source, the behavior changes.  If you comment out, or remove, the definition of `bar`, it works fine, with no segfault and both objects finalized.  If you delete the definition of `qux` as well, then only one of the foreign objects is finalized.

**Comment by ashinn** [comment]
Memory leaks wouldn't cause this problem.  I didn't see segfaults but did verify the finalizer ran twice for C and only once for C++.

The attached file shows the asm diff.  The problem appears to be in the sexp_register_c_type macro, which is expanding to a different value of `sexp_sizeof(cpointer)` ($81 instead of $65).  Manually tweaking just that value in the C++ generated asm fixes the issue.

Now, cpointer is a special struct because it ends in a flexible array, which is not supported by C++.  sexp.h has a conditional check on this to use `field[1]` instead of `field[]` in C++ for such arrays, and this causes the size diff.  Changing this to `field[0]` fixes the problem for g++, but this is a non-standard extension.

I can hack something for the sexp_register_c_type macro, e.g. computing the size of a dummy struct identical to cpointer but without the flexible array, or just make this a C function instead of a macro and it will work.  However, currently that particular flexible array is not being used, so I may just remove it (which I verified also fixes the issue).

[test-diff.txt](https://github.com/ashinn/chibi-scheme/files/7833430/test-diff.txt)

**Comment by dpapavas** [comment]
Sorry, I wasn't clear.  I didn't mean to imply that memory leaks caused the segmentation fault, but that I got both leaks (in the form of unfinalized foreign objects) and segfaults.  They seemed to be due to the same cause, as indeed proves to be the case.   I can confirm that all problems go away either by defining `SEXP_FLEXIBLE_ARRAY` as `[0]`, or by removing the `data` member from `struct cpointer`.

So, with regard to the issue under discussion, simply removing the `data` member, or turning `sexp_register_c_type` into a compiled function, would both be reasonable solutions, as far as I see.  (In the latter case though, note that `sexp_alloc_tagged(ctx, sexp_sizeof(cpointer)...` also appears in the code generated by the FFI, which might also cause trouble, depending on how it'll be compiled.)

More generally though, having `struct`s with different sizes, as seen from the library and application sides, does seem like an accident waiting to happen.  For instance, `sexp_alloc_bytecode` should also be affected (although it may not be intended to be used from the application side).  Although I agree that the zero-length array hack, being non-standard, shouldn't be relied upon solely, perhaps it would be a good idea to provide it optionally, via a `#define` switch.  It seems to be supported by all major compilers (at least GCC, Clang and MSVC) and although I couldn't find any explicit guarantees that the struct size will match that of C99 flexible array members, as far as I could see, after some experimentation with the [compiler explorer](https://godbolt.org/), they all seem to do so.

Alternatively, perhaps these flexible members could be implemented via a 1-length array for both C and C++.  I imagine this would lead to some memory waste in some cases, however this looks like it would only be the case in rare(?) allocations, such as for zero-length strings/vectors and the like.  This is just a guess though.

**Comment by ashinn** [comment]
There is only one empty vector, but empty strings are not currently deduped and are actually quite common.  There are also a few other uses of flexible arrays.  I don't like the idea of wasting space or of changing the C ABI for something that in practice is unlikely to be a problem, so at least for now I'm just using size 0 for C++.

I've also removed the unused body field of cpointers for good measure.

**Comment by dpapavas** [comment]
I share your sentiments concerning unnecessary waste entirely.  Thanks for the quick fix!
