### ISSUE TITLE
eval.h causes -Wpedantic to raise warnings

### ISSUE THREAD

**Issue by unmatched-paren** [ashinn/chibi-scheme#842]
When including `<chibi/eval.h>` with `-Wpedantic` enabled, several of these warnings pop up:

```
/gnu/store/8h89hdznj7kfgs03ifzdbqxlwrf6v05h-chibi-scheme-0.10/include/chibi/sexp.h:623:5: warning: invalid use of structure with flexible array member [-Wpedantic]
  623 |   } value;
      |     ^~~~~
```

This is a little annoying because it means I have to disable `-Werror` for `-Wpedantic` to get GCC to compile my program.

`<chibi/sexp.h>` also induces warnings and errors, though I'm not sure you're supposed to include it directly anyway:

```
/gnu/store/8h89hdznj7kfgs03ifzdbqxlwrf6v05h-chibi-scheme-0.10/include/chibi/sexp.h:623:5: warning: invalid use of structure with flexible array member [-Wpedantic]
  623 |   } value;
      |     ^~~~~
/gnu/store/8h89hdznj7kfgs03ifzdbqxlwrf6v05h-chibi-scheme-0.10/include/chibi/sexp.h:994:54: error: unknown type name ‘sexp_lsint_t’; did you mean ‘sexp_sint_t’?
  994 | SEXP_API sexp sexp_make_integer_from_lsint(sexp ctx, sexp_lsint_t x);
      |                                                      ^~~~~~~~~~~~
      |                                                      sexp_sint_t
/gnu/store/8h89hdznj7kfgs03ifzdbqxlwrf6v05h-chibi-scheme-0.10/include/chibi/sexp.h:995:63: error: unknown type name ‘sexp_luint_t’; did you mean ‘sexp_uint_t’?
  995 | SEXP_API sexp sexp_make_unsigned_integer_from_luint(sexp ctx, sexp_luint_t x);
      |                                                               ^~~~~~~~~~~~
      |                                                               sexp_uint_t
/gnu/store/8h89hdznj7kfgs03ifzdbqxlwrf6v05h-chibi-scheme-0.10/include/chibi/sexp.h:1000:43: error: unknown type name ‘sexp_lsint_t’; did you mean ‘sexp_sint_t’?
 1000 | SEXP_API sexp sexp_make_integer(sexp ctx, sexp_lsint_t x);
      |                                           ^~~~~~~~~~~~
      |                                           sexp_sint_t
/gnu/store/8h89hdznj7kfgs03ifzdbqxlwrf6v05h-chibi-scheme-0.10/include/chibi/sexp.h:1001:52: error: unknown type name ‘sexp_luint_t’; did you mean ‘sexp_uint_t’?
 1001 | SEXP_API sexp sexp_make_unsigned_integer(sexp ctx, sexp_luint_t x);
      |                                                    ^~~~~~~~~~~~
      |                                                    sexp_uint_t
```

Thanks for your work! :D

**Comment by mnieper** [comment]
I wouldn't say that the compiler is stupid here. `-Wpedantic` is to ensure maximal portability and the C standard is quite clear on this matter. Quoting from C18 (§ 6.7.2.1 (3)):

> A structure or union shall not contain a member with incomplete or function type (hence, a structure
shall not contain an instance of itself, but may contain a pointer to an instance of itself), except that
the last member of a structure with more than one named member may have incomplete array type;
such a structure (and any union containing, possibly recursively, a member that is such a structure)
shall not be a member of a structure or an element of an array.

If at all, it is the C standard that is stupid here.

PS: In fact, strictly speaking, Chibi's use of a union type (whether with or without flexible array members) is not fully compliant with the C standard (though probably compatible with every relevant implementation): By the C standard, allocating the memory for only part of a union and accessing union members then is UB even if the accessed union members are well inside the allocated area. In other words, the C standard allows a compiler in a situation like

```
union Union
{
 int a;
 char b[1000];
};

Union *a = malloc (sizeof (Union));

x.a = 1;
```

to use in subsequent statements the end part of the structure (which is not used by the integer value assigned) as a scratch area.  If I replaced the allocation with `Union *a = malloc (sizeof (int));`, I would get UB. I don't know of any compiler exploiting this. It is much more of a statement about how hard it is to write portable C code than a suggestion to change Chibi's source code so that it complies with the standard pedantically.

**Comment by ashinn** [comment]
Fair enough, it's the standard being stupid, since it allows trailing flexible arrays but not a union with a trailing flexible array.

I guess what I should really do is stop trying to declare these fields at all here and just compute the offset manually.  A failure of the type system, encouraging me not to use the type system.

For the second point if there were ever a compiler insane enough to break in this way we could conditionally define sexp_sizeof to include the full union size.  Or simply stop using a union and once again fall back to entirely manual memory management.

**Comment by ashinn** [comment]
OK, no more flexible arrays.  The code is now safer in theory (making -Wpedantic happier), and less safe in practice - I may well have introduced new bugs with the change.

**Comment by unmatched-paren** [comment]
On Mon Jul 4, 2022 at 2:33 PM BST, Alex Shinn wrote:
> OK, no more flexible arrays.  The code is now safer in theory (making -Wpedantic happier), and less safe in practice - I may well have introduced new bugs with the change.

Thank you! :D

    -- (
