### ISSUE TITLE
(chibi shell): the need to unquote in << is surprising

### ISSUE THREAD

**Issue by dpk** [ashinn/chibi-scheme#862]
```scheme
> (define foo "bar")
> (shell->string cat (<< foo))
"foo"
> (shell->string cat (<< ,foo))
"bar"
```

I’m not sure why the `` ` `` is there and why the `,` is needed. It’s not documented and I don’t understand what purpose it serves compared to just passing the expression straight to `display`.

https://github.com/ashinn/chibi-scheme/blob/e88374aae1bac29b834a255afe7df07f0f29378a/lib/chibi/shell.scm#L438

**Comment by ashinn** [comment]
This is the SCSH syntax.  My first iterations of this library broke from SCSH and required manual quoting everywhere.  It turns out it's more convenient to have the implicit quasiquote, since commands and options are more common than dynamic arguments.

We could make the argument to `<<` inconsistent with the rest of the syntax and _not_ be implicitly quasiquoted, but that's confusing and still inconsistent with SCSH, e.g. the `(<< (A five element list))` example.  Probably the unquoted form is more common but I think not enough so to make this a special case.

Sorry the docs are quite sparse, basically punting to "see SCSH's run," I will improve them if I find time.
