### ISSUE TITLE
sexp_destroy_context never returns during shutdown

### ISSUE THREAD

**Issue by mars2klb** [ashinn/chibi-scheme#882]
When exiting, it seems that `sexp_destroy_context` never returns.

On linux, this _appears_ to be ok, because the exit code is 0. But on plan9 this causes failures because `exits` is not called correctly, so the exit is considered a failure.

For testing, I just put some print statements in `main.c` (around the function calls near line 658)
Tested on 9front and Void Linux.

All I do is go into the repl, then exit. Messages are emitted up to `main.c:658`, but the process exits before the rest is executed.

If I enable `SEXP_USE_GLOBAL_HEAP`, messages _after_ are emitted as expected.

**Comment by ashinn** [comment]
On Linux, OSX and other regularly used platforms, of course `sexp_destroy_context` returns, otherwise we're either crashing or looping.  So if it doesn't return, this would likely be from some memory corruption or misalignment in Plan9 causing the gc to loop.

There is no code path calling `exit` from `sexp_destroy_context`.

**Comment by ashinn** [comment]
Ah, you're probably being confused trying to use printf debugging here instead of an external debugger.

`sexp_destroy_context` finalizes everything, including all open ports, so after it returns stdout and stderr are closed.

**Comment by mars2klb** [comment]
You are 100% correct! Sorry about the noise.
